---
# performYumUpdateRebootServer.yml
# performs yum update and reboots server
- name: perform yum update / reboot server
  hosts: frkqa000838.bpc.broadcom.net
  remote_user: lnxcfg
  become: true
  become_method: sudo
  become_user: root
 
  tasks:
        - name: Perform yum update of all packages
          yum:
            name: '*'
            state: latest
        - name: Reboot server
          command: /sbin/shutdown -r +1
          ignore_errors: true
